### ISSUE TITLE
How to change the language of this miniprofile?

### ISSUE THREAD

**Issue by obscurefreeman** [gamer2810/steam-miniprofile#9]
I can only change the text of default miniprofile in html. Can you fix this? I really like this beautiful profile.

**Comment by gamer2810** [comment]
Thanks for the suggestion @obscurefreeman 👍 
Found a way to manipulate miniprofile language using the `Steam_Language` cookie. I will find time to add this feature.

- [ ] Add cookie support on proxy server
- [ ] Add language query param support for github pages endpoint

**Comment by gamer2810** [comment]
Added multilingual, you can try chinese using 
`https://gamer2810.github.io/steam-miniprofile/?lang=schinese`
or `https://gamer2810.github.io/steam-miniprofile/?lang=tchinese`.

**Comment by obscurefreeman** [comment]
Thanks💕💕💕 @gamer2810
